// ActionTypes.js

export const CREATE_QUARRY_REQUEST = "CREATE_QUARRY_REQUEST";
export const CREATE_QUARRY_SUCCESS = "CREATE_QUARRY_SUCCESS";
export const CREATE_QUARRY_FAILURE = "CREATE_QUARRY_FAILURE";

export const GET_ALL_QUARRIES_REQUEST = "GET_ALL_QUARRIES_REQUEST";
export const GET_ALL_QUARRIES_SUCCESS = "GET_ALL_QUARRIES_SUCCESS";
export const GET_ALL_QUARRIES_FAILURE = "GET_ALL_QUARRIES_FAILURE";

export const DELETE_QUARRY_REQUEST = "DELETE_QUARRY_REQUEST";
export const DELETE_QUARRY_SUCCESS = "DELETE_QUARRY_SUCCESS";
export const DELETE_QUARRY_FAILURE = "DELETE_QUARRY_FAILURE";

export const UPDATE_QUARRY_REQUEST = "UPDATE_QUARRY_REQUEST";
export const UPDATE_QUARRY_SUCCESS = "UPDATE_QUARRY_SUCCESS";
export const UPDATE_QUARRY_FAILURE = "UPDATE_QUARRY_FAILURE";

export const GET_QUARRY_BY_ID_REQUEST = "GET_QUARRY_BY_ID_REQUEST";
export const GET_QUARRY_BY_ID_SUCCESS = "GET_QUARRY_BY_ID_SUCCESS";
export const GET_QUARRY_BY_ID_FAILURE = "GET_QUARRY_BY_ID_FAILURE";

export const GET_QUARRY_BY_USER_ID_REQUEST =
  "GET_QUARRY_BY_USER_ID_REQUEST";
export const GET_QUARRY_BY_USER_ID_SUCCESS =
  "GET_QUARRY_BY_USER_ID_SUCCESS";
export const GET_QUARRY_BY_USER_ID_FAILURE =
  "GET_QUARRY_BY_USER_ID_FAILURE";

export const UPDATE_QUARRY_STATUS_REQUEST =
  "UPDATE_QUARRY_STATUS_REQUEST";
export const UPDATE_QUARRY_STATUS_SUCCESS =
  "UPDATE_QUARRY_STATUS_SUCCESS";
export const UPDATE_QUARRY_STATUS_FAILURE =
  "UPDATE_QUARRY_STATUS_FAILURE";

  export const CREATE_EVENTS_REQUEST = "CREATE_EVENTS_REQUEST";
  export const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS";
  export const CREATE_EVENTS_FAILURE = "CREATE_EVENTS_FAILURE";

  export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
  export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
  export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";

  export const DELETE_EVENTS_REQUEST = "DELETE_EVENTS_REQUEST";
  export const DELETE_EVENTS_SUCCESS = "DELETE_EVENTS_SUCCESS";
  export const DELETE_EVENTS_FAILURE = "DELETE_EVENTS_FAILURE";

  export const GET_QUARRIES_EVENTS_REQUEST = "GET_QUARRIES_EVENTS_REQUEST";
  export const GET_QUARRIES_EVENTS_SUCCESS = "GET_QUARRIES_EVENTS_SUCCESS";
  export const GET_QUARRIES_EVENTS_FAILURE = "GET_QUARRIES_EVENTS_FAILURE";

  export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
  export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
  export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

  export const GET_QUARRIES_CATEGORY_REQUEST = "GET_QUARRIES_CATEGORY_REQUEST";
  export const GET_QUARRIES_CATEGORY_SUCCESS = "GET_QUARRIES_CATEGORY_SUCCESS";
  export const GET_QUARRIES_CATEGORY_FAILURE = "GET_QUARRIES_CATEGORY_FAILURE";