export const CREATE_LORRY_REQUEST = 'CREATE_LORRY_REQUEST';
export const CREATE_LORRY_SUCCESS = 'CREATE_LORRY_SUCCESS';
export const CREATE_LORRY_FAILURE = 'CREATE_LORRY_FAILURE';

export const GET_LORRIES_BY_QUARRY_ID_REQUEST = 'GET_LORRIES_BY_QUARRY_ID_REQUEST';
export const GET_LORRIES_BY_QUARRY_ID_SUCCESS = 'GET_LORRIES_BY_QUARRY_ID_SUCCESS';
export const GET_LORRIES_BY_QUARRY_ID_FAILURE = 'GET_LORRIES_BY_QUARRY_ID_FAILURE';

export const DELETE_LORRY_REQUEST = 'DELETE_LORRY_REQUEST';
export const DELETE_LORRY_SUCCESS = 'DELETE_LORRY_SUCCESS';
export const DELETE_LORRY_FAILURE = 'DELETE_LORRY_FAILURE';

export const SEARCH_LORRY_REQUEST = 'SEARCH_LORRY_REQUEST';
export const SEARCH_LORRY_SUCCESS = 'SEARCH_LORRY_SUCCESS';
export const SEARCH_LORRY_FAILURE = 'SEARCH_LORRY_FAILURE';

export const UPDATE_LORRY_AVAILABILITY_REQUEST = 'UPDATE_LORRY_AVAILABILITY_REQUEST';
export const UPDATE_LORRY_AVAILABILITY_SUCCESS = 'UPDATE_LORRY_AVAILABILITY_SUCCESS';
export const UPDATE_LORRY_AVAILABILITY_FAILURE = 'UPDATE_LORRY_AVAILABILITY_FAILURE';



export const GET_AVAILABLE_LORRIES_REQUEST = 'GET_AVAILABLE_LORRIES_REQUEST';
export const GET_AVAILABLE_LORRIES_SUCCESS = 'GET_AVAILABLE_LORRIES_SUCCESS';
export const GET_AVAILABLE_LORRIES_FAILURE = 'GET_AVAILABLE_LORRIES_FAILURE';
