
server:
  port: 5454

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Quarry
    username: root
    password: Lidigu@12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
    open-in-view: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: manuleedes@gmail.com
    password: Lidigu4182
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

stripe:
  api:
    key: sk_test_51QxRppQO5yqa0GmivRNnYh2cWbtVfYdpSYmPA7kMZk6Z3fF8CTBr2ZiWjTqchUQTn4Aj7M53riSILDcBwoiWBdxz00StnmJ1BF

